### ISSUE TITLE
I don't want to show Dependency-Track Project on Jenkins

### ISSUE THREAD

**Issue by cl-emanuele-ferrara** [jenkinsci/dependency-track-plugin#192]
I have integrated dependency track on **Jenkins** but I want to show only the vulnerability report (**Dependency-Track Report**) in Jenkins pipeline, I don't want to show the link to the project in the application (**Dependency-Track Project**)
![image](https://github.com/DependencyTrack/dependency-track/assets/103640930/10d6413e-8782-416f-9909-0b4923a5b244)

I don't want to show, therefore, not even the writing "These results may not be up to date. Please visit the Dependency-Track project page for most recent results" 
![image](https://github.com/DependencyTrack/dependency-track/assets/103640930/1f4c96dc-2809-4ca1-a53c-4c32fc89135a)

Is it possible to do it?
I tried changing the permissions in the Teams section, but if I try to remove "View_Vulnerability/View_Portfolio" the Dependency-Track Report is also removed (but I want this).

**Comment by sephiroth-j** [comment]
This can be achieved using CSS. Custom CSS rules can be applied with the help of the [Simple Theme plugin](https://plugins.jenkins.io/simple-theme-plugin/).

**hide links**
The links can be already hidden using one of the following rules, depending on which link you want to hide.

```css
#side-panel #tasks .task-link[href$="dependency-track-findings"] {
        display: none;
}
#side-panel #tasks .task-link[href^="https://your-dt-host"] {
        display: none;
}
```

**hide warning box**
Hiding the warning box could also be done now but with the chance to also hide elements that are not related to the DT plugin. Therefore I decided to add a no-op css class "dt-warning" which helps to identify the box without side effects. The following rule will work as of version 5.0.

```css
#main-panel > .alert.alert-warning.dt-warning {
        display: none;
}
```
